ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ninNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ninVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bvnNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bvnVerified" BOOLEAN NOT NULL DEFAULT false;
