providers = ['node']

[phases.setup]
nixPkgs = ['nodePackages.pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm --filter @percel/web build']

[start]
cmd = 'pnpm --filter @percel/web start'
