import type { Hub, Route } from '@/types/hubs';

export const hubs: Hub[] = [
  {
    id: 'hub-lagos-ojuelegba',
    name: 'Ojuelegba Hub',
    city: 'Lagos',
    state: 'Lagos',
    address: '12 Adeniran Ogunsanya, Surulere, Lagos',
    lat: 6.5029,
    lng: 3.3617,
    type: 'office',
    contactPhone: '+234 901 000 1101',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'hub-abuja-utako',
    name: 'Utako Hub',
    city: 'Abuja',
    state: 'FCT',
    address: '23 Ademola Adetokunbo Crescent, Wuse 2, Abuja',
    lat: 9.0819,
    lng: 7.4211,
    type: 'office',
    contactPhone: '+234 901 000 1102',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'hub-portharcourt-gra',
    name: 'GRA Hub',
    city: 'Port Harcourt',
    state: 'Rivers',
    address: '7 Forces Avenue, GRA Phase 2, Port Harcourt',
    lat: 4.8156,
    lng: 7.0498,
    type: 'agent',
    contactPhone: '+234 901 000 1103',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'hub-kano-gyadi-gyadi',
    name: 'Gyadi Gyadi Hub',
    city: 'Kano',
    state: 'Kano',
    address: '11 Muhammadu Buhari Way, Gyadi Gyadi, Kano',
    lat: 12.0022,
    lng: 8.5718,
    type: 'partner_park',
    contactPhone: '+234 901 000 1104',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'hub-ibadan-ring-road',
    name: 'Ring Road Hub',
    city: 'Ibadan',
    state: 'Oyo',
    address: '84 Ring Road, Ibadan, Oyo State',
    lat: 7.3775,
    lng: 3.947,
    type: 'office',
    contactPhone: '+234 901 000 1105',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
];

export const routes: Route[] = [
  {
    id: 'route-lagos-abuja',
    originHubId: 'hub-lagos-ojuelegba',
    destinationHubId: 'hub-abuja-utako',
    baseFare: 6500,
    estimatedDays: 2,
    isActive: true,
  },
  {
    id: 'route-lagos-ibadan',
    originHubId: 'hub-lagos-ojuelegba',
    destinationHubId: 'hub-ibadan-ring-road',
    baseFare: 2800,
    estimatedDays: 1,
    isActive: true,
  },
  {
    id: 'route-abuja-portharcourt',
    originHubId: 'hub-abuja-utako',
    destinationHubId: 'hub-portharcourt-gra',
    baseFare: 7200,
    estimatedDays: 2,
    isActive: true,
  },
  {
    id: 'route-kano-abuja',
    originHubId: 'hub-kano-gyadi-gyadi',
    destinationHubId: 'hub-abuja-utako',
    baseFare: 8400,
    estimatedDays: 3,
    isActive: true,
  },
  {
    id: 'route-portharcourt-ibadan',
    originHubId: 'hub-portharcourt-gra',
    destinationHubId: 'hub-ibadan-ring-road',
    baseFare: 7600,
    estimatedDays: 2,
    isActive: true,
  },
];
